persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# เปิด Port 1883 ให้ Backend และ Hardware คุยกัน
listener 1883
allow_anonymous true

# เปิด Port 9001 สำหรับ WebSocket (เผื่อใช้เชื่อมต่อผ่านเว็บในอนาคต)
listener 9001
protocol websockets