// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(LinenDbContext))]
    [Migration("20260210073658_UpdateModelsForIoT")]
    partial class UpdateModelsForIoT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DamageReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reason_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_name");

                    b.HasKey("ReasonId");

                    b.ToTable("damage_reasons", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hospital_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hospital_name");

                    b.HasKey("HospitalId");

                    b.ToTable("hospitals", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Linen", b =>
                {
                    b.Property<int>("LinenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("linen_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinenId"));

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_location");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastWashDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_wash_date");

                    b.Property<int>("MaxWashCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_wash_count");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("RfidCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rfid_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.Property<int>("WashCount")
                        .HasColumnType("integer")
                        .HasColumnName("wash_count");

                    b.HasKey("LinenId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("linens");
                });

            modelBuilder.Entity("Backend.Models.LinenLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActivityType")
                        .HasColumnType("text")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FromLocation")
                        .HasColumnType("text")
                        .HasColumnName("from_location");

                    b.Property<int>("LinenId")
                        .HasColumnType("integer")
                        .HasColumnName("linen_id");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("integer")
                        .HasColumnName("reader_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("StatusAfter")
                        .HasColumnType("text")
                        .HasColumnName("status_after");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToLocation")
                        .HasColumnType("text")
                        .HasColumnName("to_location");

                    b.HasKey("LogId");

                    b.HasIndex("LinenId");

                    b.HasIndex("ReaderId");

                    b.HasIndex("RoomId");

                    b.ToTable("linen_logs");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("DefaultRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("default_room_id");

                    b.Property<int>("MaxLifespanDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWashCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("SizeSpec")
                        .HasColumnType("text")
                        .HasColumnName("size_spec");

                    b.Property<decimal?>("StandardWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("standard_weight_kg");

                    b.Property<string>("UnitName")
                        .HasColumnType("text")
                        .HasColumnName("unit_name");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultRoomId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Reader", b =>
                {
                    b.Property<int>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reader_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReaderId"));

                    b.Property<string>("CurrentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_mode");

                    b.Property<int?>("InstalledAtRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("installed_at_room_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("OperatingDays")
                        .HasColumnType("text")
                        .HasColumnName("operating_days");

                    b.Property<TimeOnly?>("OperatingEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("operating_end_time");

                    b.Property<TimeOnly?>("OperatingStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("operating_start_time");

                    b.Property<string>("ReaderFunction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reader_function");

                    b.Property<string>("ReaderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reader_name");

                    b.Property<string>("ReaderType")
                        .HasColumnType("text")
                        .HasColumnName("reader_type");

                    b.HasKey("ReaderId");

                    b.HasIndex("InstalledAtRoomId");

                    b.ToTable("readers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("current_status_id");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dispatch_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("RequestCode")
                        .HasColumnType("text")
                        .HasColumnName("request_code");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer")
                        .HasColumnName("request_type");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TargetWardId")
                        .HasColumnType("integer")
                        .HasColumnName("target_ward_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RequestId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TargetWardId");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("Backend.Models.RequestItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("DamageReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_reason_id");

                    b.Property<int?>("LinenId")
                        .HasColumnType("integer")
                        .HasColumnName("linen_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_requested");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.HasKey("ItemId");

                    b.HasIndex("DamageReasonId");

                    b.HasIndex("LinenId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_items");
                });

            modelBuilder.Entity("Backend.Models.RequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("request_statuses", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_name");

                    b.Property<int>("WardId")
                        .HasColumnType("integer")
                        .HasColumnName("ward_id");

                    b.HasKey("RoomId");

                    b.HasIndex("WardId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("setting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SpecialTag", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TargetStatus")
                        .HasColumnType("text")
                        .HasColumnName("target_status");

                    b.HasKey("TagId");

                    b.ToTable("special_tags", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("system_logs");
                });

            modelBuilder.Entity("Backend.Models.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TitleId"));

                    b.Property<string>("TitleNameEn")
                        .HasColumnType("text")
                        .HasColumnName("title_name_en");

                    b.Property<string>("TitleNameTh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_name_th");

                    b.HasKey("TitleId");

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("integer")
                        .HasColumnName("hospital_id");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("otp_expiry");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int?>("WardId")
                        .HasColumnType("integer")
                        .HasColumnName("ward_id");

                    b.HasKey("UserId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TitleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorId"));

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.HasKey("VendorId");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ward_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WardId"));

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer")
                        .HasColumnName("hospital_id");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ward_name");

                    b.HasKey("WardId");

                    b.HasIndex("HospitalId");

                    b.ToTable("wards");
                });

            modelBuilder.Entity("Backend.Models.Linen", b =>
                {
                    b.HasOne("Backend.Models.Hospital", "Hospital")
                        .WithMany("Linens")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Linens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Vendor", "Vendor")
                        .WithMany("Linens")
                        .HasForeignKey("VendorId");

                    b.Navigation("Hospital");

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Backend.Models.LinenLog", b =>
                {
                    b.HasOne("Backend.Models.Linen", "Linen")
                        .WithMany()
                        .HasForeignKey("LinenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Reader", "Reader")
                        .WithMany("LinenLogs")
                        .HasForeignKey("ReaderId");

                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("LinenLogs")
                        .HasForeignKey("RoomId");

                    b.Navigation("Linen");

                    b.Navigation("Reader");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Room", "DefaultRoom")
                        .WithMany("Products")
                        .HasForeignKey("DefaultRoomId");

                    b.Navigation("Category");

                    b.Navigation("DefaultRoom");
                });

            modelBuilder.Entity("Backend.Models.Reader", b =>
                {
                    b.HasOne("Backend.Models.Room", "InstalledAtRoom")
                        .WithMany("Readers")
                        .HasForeignKey("InstalledAtRoomId");

                    b.Navigation("InstalledAtRoom");
                });

            modelBuilder.Entity("Backend.Models.Request", b =>
                {
                    b.HasOne("Backend.Models.RequestStatus", "CurrentStatus")
                        .WithMany("Requests")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ward", "TargetWard")
                        .WithMany()
                        .HasForeignKey("TargetWardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStatus");

                    b.Navigation("RequestedByUser");

                    b.Navigation("TargetWard");
                });

            modelBuilder.Entity("Backend.Models.RequestItem", b =>
                {
                    b.HasOne("Backend.Models.DamageReason", "DamageReason")
                        .WithMany("RequestItems")
                        .HasForeignKey("DamageReasonId");

                    b.HasOne("Backend.Models.Linen", "Linen")
                        .WithMany()
                        .HasForeignKey("LinenId");

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("RequestItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Request", "Request")
                        .WithMany("RequestItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageReason");

                    b.Navigation("Linen");

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.HasOne("Backend.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Backend.Models.SystemLog", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.Hospital", null)
                        .WithMany("Users")
                        .HasForeignKey("HospitalId");

                    b.HasOne("Backend.Models.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("Backend.Models.Title", null)
                        .WithMany("Users")
                        .HasForeignKey("TitleId");
                });

            modelBuilder.Entity("Backend.Models.Ward", b =>
                {
                    b.HasOne("Backend.Models.Hospital", "Hospital")
                        .WithMany("Wards")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.DamageReason", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("Backend.Models.Hospital", b =>
                {
                    b.Navigation("Linens");

                    b.Navigation("Users");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("Linens");

                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("Backend.Models.Reader", b =>
                {
                    b.Navigation("LinenLogs");
                });

            modelBuilder.Entity("Backend.Models.Request", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("Backend.Models.RequestStatus", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Navigation("LinenLogs");

                    b.Navigation("Products");

                    b.Navigation("Readers");
                });

            modelBuilder.Entity("Backend.Models.Title", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Vendor", b =>
                {
                    b.Navigation("Linens");
                });
#pragma warning restore 612, 618
        }
    }
}
